/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminotpad;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author bgc
 */
public class Options extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    public Options() {
        FileReader reader = null;
        String dbtype = null;          // = "sqlserver";
        String dbserv = null;          // = "BLAISE-PC";
        long dbport = 1;                // = 1433;
        String dbname = null;          // = "sqlsupport.dbo";
        String usrnam = null;          // = "usersupport";
        String psswrd = null;          // = "azerty";
        try {
            initComponents();
            String filePath = "src/doc/config.json";
            // read the json file
            reader = new FileReader(filePath);
            JSONParser jsonParser = new JSONParser();
            JSONObject jsonObject = null;
            try {
                jsonObject = (JSONObject) jsonParser.parse(reader);
            } catch (IOException ex) {
                Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
            }
            // get a String from the JSON object
            dbtype = (String) jsonObject.get("dbtype");
            dbserv = (String) jsonObject.get("dbserv");
            dbname = (String) jsonObject.get("dbname");
            usrnam = (String) jsonObject.get("usrnam");
            psswrd = (String) jsonObject.get("psswrd");
            // get a number from the JSON object
            dbport = (long) jsonObject.get("dbport");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            // chargement de la classe du pilote
            switch (dbtype) {
                case "sqlserver":
                    jRadioButtonMSSQL.setSelected(true);
                    jRadioButtonMYSQL.setSelected(false);
                    break;
                case "mysql":
                    jRadioButtonMYSQL.setSelected(true);
                    jRadioButtonMSSQL.setSelected(false);
                default:
                    /**/
                    System.out.println("Pas de base de donnée valide sélectionnée");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextFieldSrvName.setText(dbserv);
        jTextFieldbdd.setText(dbname);
        jTextFielduser.setText(usrnam);
        jTextFieldpwd.setText(psswrd);
        jTextFieldsrvPort.setText(Long.toString(dbport));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRecord = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonMSSQL = new javax.swing.JRadioButton();
        jRadioButtonMYSQL = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldpwd = new javax.swing.JTextField();
        jTextFielduser = new javax.swing.JTextField();
        jTextFieldsrvPort = new javax.swing.JTextField();
        jTextFieldSrvName = new javax.swing.JTextField();
        jTextFieldbdd = new javax.swing.JTextField();

        setTitle("Options");
        setResizable(false);

        jButtonRecord.setText("Enregistrer");
        jButtonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Annuler");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Base de données");

        jRadioButtonMSSQL.setText("SQL Serveur");
        jRadioButtonMSSQL.setName("selectSQL"); // NOI18N
        jRadioButtonMSSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMSSQLActionPerformed(evt);
            }
        });

        jRadioButtonMYSQL.setText("MySQL");
        jRadioButtonMYSQL.setName("selectSQL"); // NOI18N
        jRadioButtonMYSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMYSQLActionPerformed(evt);
            }
        });

        jLabel2.setText("Serveur");

        jLabel3.setText("Port");

        jLabel4.setText("Nom");

        jLabel5.setText("Utilisateur");

        jLabel6.setText("Mot de passe");

        jTextFieldsrvPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsrvPortActionPerformed(evt);
            }
        });

        jTextFieldSrvName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSrvNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRecord))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButtonMSSQL)
                            .addComponent(jRadioButtonMYSQL)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSrvName)
                                    .addComponent(jTextFieldsrvPort)
                                    .addComponent(jTextFieldbdd)
                                    .addComponent(jTextFielduser)
                                    .addComponent(jTextFieldpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jRadioButtonMYSQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMSSQL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSrvName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldsrvPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldbdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFielduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(jTextFieldpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonRecord))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldSrvNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSrvNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSrvNameActionPerformed

    private void jTextFieldsrvPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsrvPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsrvPortActionPerformed

    private void jRadioButtonMSSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMSSQLActionPerformed
        // TODO add your handling code here:
        jRadioButtonMSSQL.setSelected(true);
        jRadioButtonMYSQL.setSelected(false);
    }//GEN-LAST:event_jRadioButtonMSSQLActionPerformed

    private void jRadioButtonMYSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMYSQLActionPerformed
        // TODO add your handling code here:
        jRadioButtonMYSQL.setSelected(true);
        jRadioButtonMSSQL.setSelected(false);
    }//GEN-LAST:event_jRadioButtonMYSQLActionPerformed

    private void jButtonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordActionPerformed
        // TODO add your handling code here:
        String dbtype;
        String srvname;
        String srvport;
        String dbname;
        String user;
        String pwd;

        if (jRadioButtonMSSQL.isSelected()) {
            dbtype = "sqlserver";
        } else if (jRadioButtonMYSQL.isSelected()) {
            dbtype = "mysql";
        } else {
            dbtype = "mysql";
        }
        srvname = jTextFieldSrvName.getText();
        srvport = jTextFieldsrvPort.getText();
        dbname = jTextFieldbdd.getText();
        user = jTextFielduser.getText();
        pwd = jTextFieldpwd.getText();

        String cheminDuFichier = "src/doc/config.json";

        String jsonContent = "{"
                + "\"dbtype\":\"" + dbtype + "\""
                + ",\"dbserv\":\"" + srvname + "\""
                + ",\"dbport\":" + srvport + ""
                + ",\"dbname\":\"" + dbname + "\""
                + ",\"usrnam\":\"" + user + "\""
                + ",\"psswrd\":\"" + pwd + "\""
                + "}";
        
        Fichier file = new Fichier(cheminDuFichier, jsonContent);
        file.fileWrite();

        this.setVisible(false);
    }//GEN-LAST:event_jButtonRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonMSSQL;
    private javax.swing.JRadioButton jRadioButtonMYSQL;
    private javax.swing.JTextField jTextFieldSrvName;
    private javax.swing.JTextField jTextFieldbdd;
    private javax.swing.JTextField jTextFieldpwd;
    private javax.swing.JTextField jTextFieldsrvPort;
    private javax.swing.JTextField jTextFielduser;
    // End of variables declaration//GEN-END:variables
}
